version: "3.7"
services:
  fg-auto-update:
    build:
      context: .
      dockerfile: Dockerfile
    image: fg-auto-update
    container_name: fg-auto-update
    volumes:
      - ./<your function folder>:/function 
    environment:
      - ACCESS_KEY=
      - SECRET_KEY=
      - REGION=
      - PROJECT=
      - FUNC_NAME=
      - DEPENDENCIES=
      - HANDLER=
      - RUNTIME=
      - MEMORY_SIZE=
      - TIMEOUT=
      - FUNCTION_FOLDER=
    env_file:
      - .env
