version: "3.7"
services:
  fg-auto-update:
    build:
      context: .
      dockerfile: Dockerfile
    image: fg-auto-update
    container_name: fg-auto-update
    volumes:
      - ./function:/app/function # This is the folder where your code is located
    environment:
      - ACCESS_KEY=
      - SECRET_KEY=
      - REGION=
      - PROJECT_ID=
      - FUNC_NAME=
      - DEPENDENCIES=
      - HANDLER=
      - RUNTIME=
      - MEMORY_SIZE=
      - TIMEOUT=
    env_file:
      - .env
